### PR TITLE
Fix README.md missing `hide_icon` setting

### PR DESCRIPTION
**Pull request by jennydaman**

### CODE REVIEW

**Comment by Kirottu** [comment]
There are 2 instances of the example config in the readme, so the PR should add the missing option to both of them.

**Comment by jennydaman** [comment]
@Kirottu done.

Though on second thought, I think it would be better for `anyrun` to instead tolerate missing config values i.e. have a default value for each config. What do you think?

**Comment by Bryntet** [comment]
+1 for this

style.css has default values, config.ron should have them too

**Comment by Kirottu** [comment]
I'd say the problem with a default `config.ron` would be the list of plugins, technically it could just be a few of the ones included in this repo but I am not completely sure about that. Actually implementing it if a set of default values is decided on is trivial though.

But as the PR is fine now I shall merge it.

**Pull request merged**
