### PR TITLE
added option for fullscreen window

### PR DESCRIPTION
**Pull request by abenz1267**
I've added "Fullscreen" as an Option for "Position". I couldn't figure out how to ignore other exclusive zones though, f.e. Waybar.

### CODE REVIEW

**Comment by abenz1267** [comment]
One could force an actual fullscreen ignoring f.e. waybars exclusive zone, by setting a negative margin.

In that case one would need 2 config vars: anchor and size (...of the bar).

**Comment by Kirottu** [comment]
I think the method of determining position/sizes could be reworked to make it so that there is no redundant config options (like `width` as in the case of the `Fullscreen` position), and as you noticed by setting the exclusive zone to `-1` other exclusive zones can be ignored.

**Comment by abenz1267** [comment]
> I think the method of determining position/sizes could be reworked to make it so that there is no redundant config options (like `width` as in the case of the `Fullscreen` position), and as you noticed by setting the exclusive zone to `-1` other exclusive zones can be ignored.

I don't think "width" is redundant in fullscreen mode, the problem is rather that it's not doing what you think it'd do. Setting the position to fullscreen and setting width... i'd expect width to be the actual input width.

Maybe this is a general problem with the width config parameter.

**Comment by abenz1267** [comment]
Now that i think about it. I think the actual window should ALWAYS be fullscreen regardless. And the inner window with the prompt and list should be positioned based on config and styling.

**Comment by abenz1267** [comment]
I've actually done the following now:

1. Layer window is ALWAYS fullscreen
2. config width = width of box#main
3. removed positioning for now (always anchored top, centered horizontally). Positioning from top can be done via CSS.

image

With this approach you can achieve this easily. A proper "centered" mode with an optional offset would be good though. But I don't know how you'd do that without being janky if results are shown.

**Comment by abenz1267** [comment]
I've added the config options for layer and ignoring exclusive zones.

**Comment by Kirottu** [comment]
Alright perfect, and I think I may have gotten the positioning to work. So I added the previous `Top` and `Center` positions, along with a variable for the vertical offset of the main vbox widget. I'll still need to try this out on my multi-monitor setup, and a percentage based offset option could be a good idea as well.

Can you give me push access to the fork so I can just push my work to the branch that this PR is based on? And then you can test it as well.

**Comment by abenz1267** [comment]
Perfect! Tested it and it seems to work fine.

**Comment by abenz1267** [comment]
What's the status here?

**Pull request merged**
